// Rebuilds the data files the promo page loads as classic scripts, so the
// page keeps working when opened straight from disk (file:// cannot fetch).
//
//   node promo/tools/build-assets.mjs                         # sounds only
//   node promo/tools/build-assets.mjs --land land-110m.json   # + world map
//   node promo/tools/build-assets.mjs --fonts <dir>           # + fonts
//
// Sounds come from the game's own sample pack (public/sounds/v1). The world
// map is Natural Earth's 1:110m land, as shipped by the `world-atlas` npm
// package (`npm pack world-atlas@2`), rasterised onto a 2° grid: one bit per
// cell, 90 rows × 180 columns. Fonts are Cormorant Garamond and Manrope (SIL
// OFL 1.1, licences in assets/) from the Fontsource packages: unpack
// `npm pack @fontsource/cormorant-garamond @fontsource/manrope` into <dir> as
// <dir>/cormorant-garamond and <dir>/manrope.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const outDir = path.resolve(here, '../assets');
fs.mkdirSync(outDir, { recursive: true });

// ---- sounds ------------------------------------------------------------------
const PACK = path.join(root, 'public/sounds/v1');
const CLIPS = [
  'djembe-loop.mp3', 'drop-1.mp3', 'drop-2.mp3', 'drop-3.mp3', 'drop-4.mp3', 'drop-5.mp3', 'drop-6.mp3',
  'drop-seeds-1.mp3', 'drop-seeds-2.mp3', 'drop-seeds-3.mp3', 'drop-seeds-4.mp3', 'drop-many.mp3',
  'scoop-2.wav', 'tap-1.wav', 'victory-1.mp3',
];
const MIME = { '.mp3': 'audio/mpeg', '.wav': 'audio/wav' };
let js = '// Generated by promo/tools/build-assets.mjs from public/sounds/v1. Do not edit.\n';
js += 'window.AWALE_PROMO_SOUNDS = {\n';
for (const file of CLIPS) {
  const bytes = fs.readFileSync(path.join(PACK, file));
  const name = file.replace(/\.[^.]+$/, '');
  js += `  '${name}': 'data:${MIME[path.extname(file)]};base64,${bytes.toString('base64')}',\n`;
}
js += '};\n';
fs.writeFileSync(path.join(outDir, 'sounds.js'), js);
console.log('wrote assets/sounds.js', (js.length / 1024).toFixed(0), 'KB');

// ---- world -------------------------------------------------------------------
const arg = name => { const i = process.argv.indexOf(name); return i > 0 ? process.argv[i + 1] : null; };
const landPath = arg('--land');
if (landPath) {
  const topo = JSON.parse(fs.readFileSync(landPath, 'utf8'));
  const { scale, translate } = topo.transform;
  const arcs = topo.arcs.map(arc => {
    let x = 0, y = 0;
    return arc.map(([dx, dy]) => { x += dx; y += dy; return [x * scale[0] + translate[0], y * scale[1] + translate[1]]; });
  });
  const arcPts = i => (i >= 0 ? arcs[i] : arcs[~i].slice().reverse());
  const rings = [];
  for (const g of topo.objects.land.geometries) {
    const polys = g.type === 'Polygon' ? [g.arcs] : g.arcs;
    for (const poly of polys) for (const ring of poly) rings.push(ring.flatMap(arcPts));
  }
  const inside = (lon, lat) => {
    let c = false;
    for (const r of rings) {
      for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
        const [xi, yi] = r[i], [xj, yj] = r[j];
        if ((yi > lat) !== (yj > lat) && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) c = !c;
      }
    }
    return c;
  };
  const bits = new Uint8Array((90 * 180) / 8);
  for (let r = 0; r < 90; r++) {
    for (let c = 0; c < 180; c++) {
      if (inside(-179 + c * 2, 89 - r * 2)) { const k = r * 180 + c; bits[k >> 3] |= 1 << (k & 7); }
    }
  }
  const out = '// Generated by promo/tools/build-assets.mjs from Natural Earth 1:110m land (world-atlas).\n'
    + '// 2° grid, 90 rows (89°N → 89°S) × 180 columns (179°W → 179°E), one bit per cell, LSB first.\n'
    + `window.AWALE_PROMO_WORLD = '${Buffer.from(bits).toString('base64')}';\n`;
  fs.writeFileSync(path.join(outDir, 'world.js'), out);
  console.log('wrote assets/world.js');
}

// ---- fonts -------------------------------------------------------------------
// Registered through the FontFace API from data URIs: works from file://, in a
// sandboxed frame and offline, and a frame never renders in a fallback face.
const fontDir = arg('--fonts');
if (fontDir) {
  const faces = [
    ['Cormorant Garamond', 'cormorant-garamond', 600, 'normal'],
    ['Cormorant Garamond', 'cormorant-garamond', 600, 'italic'],
    ['Cormorant Garamond', 'cormorant-garamond', 700, 'normal'],
    ['Cormorant Garamond', 'cormorant-garamond', 700, 'italic'],
    ['Manrope', 'manrope', 500, 'normal'],
    ['Manrope', 'manrope', 600, 'normal'],
    ['Manrope', 'manrope', 700, 'normal'],
    ['Manrope', 'manrope', 800, 'normal'],
  ];
  let out = '// Generated by promo/tools/build-assets.mjs. Cormorant Garamond and Manrope, latin subset,\n'
    + '// SIL Open Font License 1.1 (see OFL-*.txt next to this file).\n'
    + 'window.AWALE_PROMO_FONTS = [\n';
  for (const [family, pkg, weight, style] of faces) {
    const file = path.join(fontDir, pkg, 'files', `${pkg}-latin-${weight}-${style}.woff2`);
    out += `  ['${family}', ${weight}, '${style}', 'data:font/woff2;base64,${fs.readFileSync(file).toString('base64')}'],\n`;
  }
  out += '];\n';
  fs.writeFileSync(path.join(outDir, 'fonts.js'), out);
  for (const pkg of ['cormorant-garamond', 'manrope']) {
    fs.copyFileSync(path.join(fontDir, pkg, 'LICENSE'), path.join(outDir, `OFL-${pkg}.txt`));
  }
  console.log('wrote assets/fonts.js', (out.length / 1024).toFixed(0), 'KB');
}
