// The match server's brain, with no server in it.
//
// Everything a room does — seating two players, refusing an illegal move,
// deciding a game is over, handing a seat back to someone whose train went into
// a tunnel — is a pure function from (state, message) to (state, messages out).
// The Cloudflare Durable Object in `server/` is a thin socket adapter around
// this file, and so is the Node dev server. That is what makes the whole thing
// testable in `test/online.test.ts` without a cloud account.
//
// The server is authoritative on purpose. Both players run the same engine, so
// the client could be trusted to judge itself — but "could be trusted" is a
// sentence about strangers on the internet. Here, a move is legal because the
// server replayed it, not because a browser said so.
import {
  applyMove, canPlay, decideWinner, legalMoves, other,
  type Seat, type Winner,
} from './rules.ts';
import {
  stateHash, TIME_CONTROLS,
  type ClientMsg, type ClockView, type ErrorCode, type OverReason,
  type PlayerView, type RoomSnapshot, type RoomStatus, type ServerMsg, type TimeControlId,
} from './protocol.ts';
import type { CountryKey } from './country.ts';

/**
 * How long a disconnected player keeps their seat.
 *
 * Long enough to survive a tunnel, a lock screen, or a Wi-Fi/5G handover;
 * short enough that the player still staring at the board is not held hostage
 * by someone who closed the tab and went to lunch.
 */
export const ABANDON_MS = 90_000;

/** A room nobody ever joined is swept up rather than kept forever. */
export const EMPTY_ROOM_TTL_MS = 30 * 60_000;

/** How often an idle room wakes up just to check whether it can be deleted. */
export const IDLE_SWEEP_MS = 10 * 60_000;

/** No alarm is ever set closer than this — see `nextAlarmAt`. */
export const MIN_ALARM_MS = 1_000;

export interface PlayerSlot {
  /** Secret, generated by the client, stored on the client. Proves a seat. */
  token: string;
  name: string;
  online: boolean;
  /** Where the player says they play from; absent when unknown. */
  country?: CountryKey;
  /** When this seat last went offline; null while connected. */
  offlineSince: number | null;
}

export interface RoomState {
  code: string;
  status: RoomStatus;
  pits: number[];
  scores: number[];
  turn: Seat;
  ply: number;
  startSeat: Seat;
  players: [PlayerSlot | null, PlayerSlot | null];
  winner: Winner | null;
  reason: OverReason | null;
  rematch: [boolean, boolean];
  createdAt: number;
  updatedAt: number;
  // The clock. Optional because a room stored before clocks existed has none
  // of these, and must still load: missing reads as an untimed game.
  /** Set by the first player in who names one; fixed once the game starts. */
  control?: TimeControlId;
  /** Milliseconds left per seat, as of `turnStartedAt` for the side to move. */
  left?: [number, number];
  /** When the side to move started thinking; null while no clock runs. */
  turnStartedAt?: number | null;
}

/** A message and who should get it. */
export interface Effect {
  to: 'all' | Seat;
  msg: ServerMsg;
}

export interface Step {
  state: RoomState;
  effects: Effect[];
}

export interface JoinResult extends Step {
  seat: Seat | null;
  error: ErrorCode | null;
}

const freshBoard = () => Array(12).fill(4) as number[];

// Seat names the UI can show when a player joined without a nickname. The
// board turns round on a phone, so a compass label would point nowhere.
const defaultName = (seat: Seat) => (seat === 0 ? 'Player 1' : 'Player 2');

export function createRoom(code: string, now: number): RoomState {
  return {
    code,
    status: 'waiting',
    pits: freshBoard(),
    scores: [0, 0],
    turn: 0,
    ply: 0,
    startSeat: 0,
    players: [null, null],
    winner: null,
    reason: null,
    rematch: [false, false],
    createdAt: now,
    updatedAt: now,
    control: 'none',
    left: [0, 0],
    turnStartedAt: null,
  };
}

// ---- the clock ------------------------------------------------------------
//
// The server's clock is the only one that counts. A client draws a countdown
// from the last numbers it was sent, but a flag falls here: on the move that
// arrives too late, or on the alarm set for the moment the time runs out —
// whichever comes first. So a player cannot buy time by stopping their own
// clock, and a slow network costs the player whose move it is, as it would
// across a real table.

const timing = (state: RoomState) => TIME_CONTROLS[state.control ?? 'none'];

/** Both clocks as they stand at `now`, the running one counted down. */
function clockAt(state: RoomState, now: number): [number, number] {
  const left: [number, number] = [state.left?.[0] ?? 0, state.left?.[1] ?? 0];
  if (state.status === 'playing' && state.turnStartedAt != null) {
    left[state.turn] = Math.max(0, left[state.turn] - (now - state.turnStartedAt));
  }
  return left;
}

function clockView(state: RoomState, now: number): ClockView | undefined {
  if (!timing(state)) return undefined;
  const running = state.status === 'playing' && state.turnStartedAt != null ? state.turn : null;
  return { control: state.control!, left: clockAt(state, now), running };
}

/** Full time on both clocks, and the side to move's already running. */
function startClock(state: RoomState, now: number): RoomState {
  const tc = timing(state);
  if (!tc) return state;
  return { ...state, left: [tc.base, tc.base], turnStartedAt: now };
}

/** Both clocks stopped where they stand. */
function stopClock(state: RoomState, now: number): RoomState {
  if (!timing(state)) return state;
  return { ...state, left: clockAt(state, now), turnStartedAt: null };
}

/** When the side to move runs out of time, or null when no clock runs. */
export function flagAt(state: RoomState): number | null {
  if (!timing(state) || state.status !== 'playing' || state.turnStartedAt == null) return null;
  return state.turnStartedAt + (state.left?.[state.turn] ?? 0);
}

const view = (p: PlayerSlot | null): PlayerView | null =>
  (p ? { name: p.name, online: p.online, ...(p.country ? { country: p.country } : {}) } : null);

export function snapshot(state: RoomState, now: number = state.updatedAt): RoomSnapshot {
  const clock = clockView(state, now);
  return {
    room: state.code,
    status: state.status,
    pits: [...state.pits],
    scores: [...state.scores],
    turn: state.turn,
    ply: state.ply,
    startSeat: state.startSeat,
    players: [view(state.players[0]), view(state.players[1])],
    winner: state.winner,
    reason: state.reason,
    rematch: [...state.rematch] as [boolean, boolean],
    ...(clock ? { clock } : {}),
  };
}

export const seatOf = (state: RoomState, token: string): Seat | null => {
  if (state.players[0]?.token === token) return 0;
  if (state.players[1]?.token === token) return 1;
  return null;
};

/** Both seats taken and someone still connected to each. */
export const isFull = (state: RoomState): boolean =>
  state.players[0] !== null && state.players[1] !== null;

/**
 * Is one player sitting here, still connected, waiting for a second?
 *
 * The matchmaker's question. It is not "is there a free seat": a room whose
 * only occupant has closed their tab has a free seat and is still the wrong
 * place to send someone, because nobody there will ever move.
 */
export function isJoinable(state: RoomState): boolean {
  if (state.status !== 'waiting') return false;
  const seated = state.players.filter(p => p !== null);
  return seated.length === 1 && seated[0]!.online;
}

function touch(state: RoomState, now: number): RoomState {
  return { ...state, updatedAt: now };
}

/**
 * Seat a connection.
 *
 * A returning token gets its old seat back — that is the whole reconnect story.
 * A new token takes a free seat, and is refused once both are spoken for. The
 * room does not care how many sockets a seat has open; two tabs on one token
 * are one player, and both hear everything that seat hears.
 */
export function join(
  state: RoomState, token: string, name: string, now: number, country?: CountryKey,
  control?: TimeControlId,
): JoinResult {
  const existing = seatOf(state, token);
  const effects: Effect[] = [];

  if (existing !== null) {
    const players = [...state.players] as [PlayerSlot | null, PlayerSlot | null];
    players[existing] = {
      ...players[existing]!,
      name: name || players[existing]!.name,
      ...(country ? { country } : {}),
      online: true,
      offlineSince: null,
    };
    const next = touch({ ...state, players }, now);
    effects.push({ to: 'all', msg: { t: 'peer', seat: existing, player: view(players[existing]) } });
    // Coming back to a game that was still running is not a new game: this
    // snapshot rebuilds their board exactly as the server has it.
    effects.push({ to: existing, msg: { t: 'welcome', seat: existing, snapshot: snapshot(next, now) } });
    return { state: next, effects, seat: existing, error: null };
  }

  const free: Seat | null = state.players[0] === null ? 0 : state.players[1] === null ? 1 : null;
  if (free === null) {
    return { state, effects: [], seat: null, error: 'room-full' };
  }

  const players = [...state.players] as [PlayerSlot | null, PlayerSlot | null];
  players[free] = {
    token, name: name || defaultName(free), online: true, offlineSince: null,
    ...(country ? { country } : {}),
  };
  let next = touch({ ...state, players }, now);

  // The room's time control is whatever the first player to name one asked
  // for — the creator, normally, whose invite link carries it. A player who
  // joins by typing a code names none and plays at the room's.
  if (next.status === 'waiting' && (next.control ?? 'none') === 'none' && control) {
    next = { ...next, control };
  }

  // The second player through the door starts the game, and the clock.
  if (next.status === 'waiting' && players[0] && players[1]) {
    next = startClock({ ...next, status: 'playing', turn: next.startSeat }, now);
  }

  effects.push({ to: free, msg: { t: 'welcome', seat: free, snapshot: snapshot(next, now) } });
  effects.push({ to: other(free), msg: { t: 'sync', snapshot: snapshot(next, now) } });
  return { state: next, effects, seat: free, error: null };
}

/** A socket dropped. The seat is held, not freed — see `sweep`. */
export function disconnect(state: RoomState, token: string, now: number): Step {
  const seat = seatOf(state, token);
  if (seat === null) return { state, effects: [] };
  const players = [...state.players] as [PlayerSlot | null, PlayerSlot | null];
  players[seat] = { ...players[seat]!, online: false, offlineSince: now };
  const next = touch({ ...state, players }, now);
  return {
    state: next,
    effects: [{ to: 'all', msg: { t: 'peer', seat, player: view(players[seat]) } }],
  };
}

/**
 * Time-driven housekeeping: end a game whose opponent is not coming back.
 *
 * Called from an alarm, so a player left staring at "waiting for opponent"
 * gets an answer even though no message ever arrives to trigger one.
 */
export function sweep(state: RoomState, now: number): Step {
  if (state.status !== 'playing') return { state, effects: [] };
  const flag = flagAt(state);
  if (flag !== null && now >= flag) return endGame(state, other(state.turn), 'timeout', now);
  for (const seat of [0, 1] as Seat[]) {
    const p = state.players[seat];
    if (!p || p.online || p.offlineSince === null) continue;
    if (now - p.offlineSince < ABANDON_MS) continue;
    return endGame(state, other(seat), 'abandoned', now);
  }
  return { state, effects: [] };
}

/**
 * The soonest the clock has anything to say, as an absolute timestamp.
 *
 * The only true deadline a room has is the seat held for a player who
 * disconnected mid-game; everything else is a periodic tidy-up pass that ends
 * with `isExpired` deleting the room.
 *
 * The clamp to `now + MIN_ALARM_MS` is the important part. A deadline that has
 * already passed must never be scheduled at its own time: the runtime fires a
 * past alarm immediately, the handler recomputes the same past time, and the
 * object spins as fast as storage allows — hundreds of thousands of alarms and
 * writes in minutes, for one abandoned room.
 */
export function nextAlarmAt(state: RoomState, now: number): number {
  const deadlines = state.status === 'playing'
    ? [...state.players
      .map(p => (p && !p.online && p.offlineSince !== null ? p.offlineSince + ABANDON_MS : null)),
    flagAt(state)]
      .filter((t): t is number => t !== null)
    : [];

  if (deadlines.length === 0) return now + IDLE_SWEEP_MS;
  return Math.max(Math.min(...deadlines), now + MIN_ALARM_MS);
}

/** Is there any reason to keep this room in storage? */
export function isExpired(state: RoomState, now: number): boolean {
  const idle = now - state.updatedAt;
  if (state.status === 'over') return idle > EMPTY_ROOM_TTL_MS;
  if (state.players.every(p => p === null || !p.online)) return idle > EMPTY_ROOM_TTL_MS;
  return false;
}

function endGame(state: RoomState, winner: Winner, reason: OverReason, now: number): Step {
  const stopped = stopClock(state, now);
  const next = touch({
    ...stopped,
    status: 'over' as RoomStatus,
    winner,
    reason,
    rematch: [false, false] as [boolean, boolean],
  }, now);
  const clock = timing(next) ? { clock: clockAt(next, now) } : {};
  return {
    state: next,
    effects: [{ to: 'all', msg: { t: 'over', winner, reason, scores: [...next.scores], ...clock } }],
  };
}

const fail = (state: RoomState, seat: Seat, code: ErrorCode): Step =>
  ({ state, effects: [{ to: seat, msg: { t: 'err', code } }] });

/** Everything a seated player can ask the room to do. */
export function command(
  state: RoomState, token: string, msg: ClientMsg, now: number,
): Step {
  const seat = seatOf(state, token);
  if (seat === null) {
    return { state, effects: [{ to: 'all', msg: { t: 'err', code: 'not-seated' } }] };
  }

  switch (msg.t) {
    case 'ping':
      return { state, effects: [{ to: seat, msg: { t: 'pong' } }] };

    case 'resync':
      return { state, effects: [{ to: seat, msg: { t: 'sync', snapshot: snapshot(state, now) } }] };

    case 'move':
      return move(state, seat, msg.pit, msg.ply, now);

    case 'resign': {
      if (state.status !== 'playing') return fail(state, seat, 'not-playing');
      return endGame(state, other(seat), 'resign', now);
    }

    case 'rematch': {
      if (state.status !== 'over') return fail(state, seat, 'not-playing');
      const rematch = [...state.rematch] as [boolean, boolean];
      rematch[seat] = true;
      let next = touch({ ...state, rematch }, now);
      const effects: Effect[] = [{ to: other(seat), msg: { t: 'rematch', from: seat } }];
      if (rematch[0] && rematch[1]) {
        // Whoever did not open the last game opens this one. Moving first is a
        // real edge in awalé, so it alternates rather than sticking with the
        // player who happened to create the room.
        const startSeat = other(next.startSeat);
        next = startClock(touch({
          ...next,
          status: 'playing',
          pits: freshBoard(),
          scores: [0, 0],
          turn: startSeat,
          ply: 0,
          startSeat,
          winner: null,
          reason: null,
          rematch: [false, false],
        }, now), now);
        effects.push({ to: 'all', msg: { t: 'sync', snapshot: snapshot(next, now) } });
      }
      return { state: next, effects };
    }

    // `hello` is handled by `join`, before a seat exists.
    case 'hello':
      return { state, effects: [] };
  }
}

function move(state: RoomState, seat: Seat, pit: number, ply: number, now: number): Step {
  if (state.status !== 'playing') return fail(state, seat, 'not-playing');
  if (state.turn !== seat) return fail(state, seat, 'not-your-turn');

  // A move carries the ply the client believed it was answering. A stale one is
  // a duplicate from a retried send or a slow network, not a new move — dropping
  // it is what stops one tap becoming two.
  if (ply !== state.ply) return fail(state, seat, 'stale-ply');
  if (!canPlay(state.pits, seat, pit)) return fail(state, seat, 'illegal-move');

  // A move that arrives after the flag has fallen is not a move: the game was
  // already lost on time, whether or not the alarm had got there first.
  const tc = timing(state);
  const flag = flagAt(state);
  if (flag !== null && now >= flag) return endGame(state, other(seat), 'timeout', now);

  const outcome = applyMove(state.pits, state.scores, pit);
  let next = touch({
    ...state,
    pits: outcome.pits,
    scores: outcome.scores,
    turn: outcome.end ? state.turn : outcome.next,
    ply: state.ply + 1,
  }, now);

  // The mover's thinking time comes off their clock and the increment goes
  // back on; the other side's clock starts from this moment.
  let clock: { clock: [number, number] } | Record<string, never> = {};
  if (tc) {
    const left = clockAt(state, now);
    left[seat] += tc.inc;
    next = { ...next, left, turnStartedAt: outcome.end ? null : now };
    clock = { clock: [left[0], left[1]] };
  }

  const effects: Effect[] = [{
    to: 'all',
    msg: {
      t: 'move',
      pit,
      by: seat,
      ply: next.ply,
      hash: stateHash(next.pits, next.scores, next.turn),
      ...clock,
    },
  }];

  if (outcome.end) {
    const ended = endGame(next, outcome.end.winner, outcome.end.reason, now);
    next = ended.state;
    effects.push(...ended.effects);
  }

  return { state: next, effects };
}

/**
 * A safety net, not a rule: if the position ever stops adding up to 48 seeds,
 * something upstream is broken and the room should stop rather than keep
 * dealing out phantom seeds.
 */
export function isCoherent(state: RoomState): boolean {
  const total = state.pits.reduce((a, b) => a + b, 0) + state.scores[0] + state.scores[1];
  if (total !== 48) return false;
  if (state.status === 'playing' && legalMoves(state.pits, state.turn).length === 0) return false;
  if (state.status === 'over' && state.winner === null) return false;
  if (state.status === 'over' && state.reason === 'score') {
    return state.winner === decideWinner(state.scores);
  }
  return true;
}
